apiVersion: v1
kind: PersistentVolume
metadata:
  name: guestbook-mariadb-pv
  labels:
    app: mariadb
    project: guestbook
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: guestbook-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/guestbook-mariadb
    type: DirectoryOrCreate
