apiVersion: batch/v1
kind: CronJob
metadata:
  name: guestbook-cleanup
  namespace: guestbook
  labels:
    app: cleanup
    project: guestbook
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: cleanup
        project: guestbook
    spec:
      template:
        metadata:
          labels:
            app: cleanup
            project: guestbook
        spec:
          restartPolicy: Never
          containers:
            - name: cleanup
              image: mariadb:11.8
              command: ["sh", "-c", "mariadb -h $DB_HOST -P $DB_PORT -u $DB_USERNAME -p$DB_PASSWORD $DB_NAME -e \"DELETE FROM entries WHERE created_at < NOW() - INTERVAL 1 MINUTE;\""]
              env:
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: guestbook-config
                      key: DB_HOST
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: guestbook-config
                      key: DB_PORT
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: guestbook-config
                      key: DB_NAME
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: guestbook-secret
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: guestbook-secret
                      key: DB_PASSWORD
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
